<?xml version="1.0" encoding="utf-8"?><Database Name="ProjectData" Class="sahajjoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=C:\Users\Hridoy\Documents\ProjectData.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="Login_form.Properties.Settings" SettingsPropertyName="ProjectDataConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Police" Member="Polices">
    <Type Name="Police">
      <Column Name="PoliceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Area_Police" Member="Area" ThisKey="LocationId" OtherKey="LocationId" Type="Area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hospital" Member="Hospitals">
    <Type Name="Hospital">
      <Column Name="HospitalId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HospitalName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Area_Hospital" Member="Area" ThisKey="LocationId" OtherKey="LocationId" Type="Area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FireService" Member="FireServices">
    <Type Name="FireService">
      <Column Name="FireServiceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Area_FireService" Member="Area" ThisKey="LocationId" OtherKey="LocationId" Type="Area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BloodBank" Member="BloodBanks">
    <Type Name="BloodBank">
      <Column Name="BloodBankId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Area_BloodBank" Member="Area" ThisKey="LocationId" OtherKey="LocationId" Type="Area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Area" Member="Areas">
    <Type Name="Area">
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Area_Police" Member="Polices" ThisKey="LocationId" OtherKey="LocationId" Type="Police" />
      <Association Name="Area_Hospital" Member="Hospitals" ThisKey="LocationId" OtherKey="LocationId" Type="Hospital" />
      <Association Name="Area_FireService" Member="FireServices" ThisKey="LocationId" OtherKey="LocationId" Type="FireService" />
      <Association Name="Area_BloodBank" Member="BloodBanks" ThisKey="LocationId" OtherKey="LocationId" Type="BloodBank" />
      <Association Name="Area_Area" Member="Area2" ThisKey="LocationId" OtherKey="LocationId" Type="Area" Cardinality="One" />
      <Association Name="Area_Ambulance" Member="Ambulances" ThisKey="LocationId" OtherKey="LocationId" Type="Ambulance" />
      <Association Name="Area_Area" Member="Area1" ThisKey="LocationId" OtherKey="LocationId" Type="Area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ambulance" Member="Ambulances">
    <Type Name="Ambulance">
      <Column Name="AmbulanceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AmbulanceName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Area_Ambulance" Member="Area" ThisKey="LocationId" OtherKey="LocationId" Type="Area" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="LoginId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecurityQuestion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>